### ISSUE TITLE
data preprocessing

### ISSUE THREAD

**Issue by vikneo2017** [sovaai/sova-tts-engine#2]
When you start training with the "Natalia" dataset, kindly provided by the link in your article on Habr. I specify the path to the dataset files in the hparams.yaml:

`load_mel_from_disk: False
audios_path: 'wavs/'
alignments_path:
  original:
  stressed:
training_files: 'train'
validation_files: 'val'

charset: "ru_trans" # possible entries: en, ru, ru_trans
text_handler_cfg: data/text_handler_cfg.yaml`

Please, сan you tell me in what format you need to submit data to the engine and how to prepare it correctly?
Can this be due to the lack of dictionaries in the data/stress.dict Handler configuration?

**Comment by Dekakhrone** [comment]
Problem with python support (current version requires python<=3.7). I will add support for newer python versions soon.

**Comment by Dekakhrone** [comment]
New version of the tps package is ready to use (fixed enum containment checks for python > 3.7).
